from setuptools import setup, find_namespace_packages

scm_version_template = """# Generated by setuptools_scm
__all__ = ["__version__"]

__version__ = "{version}"
"""

setup(
    name="ts_atmonochromator",
    description="MonochromatorCsc ATMonochromator.",
    use_scm_version={
        "write_to": "python/lsst/ts/atmonochromator/version.py",
        "write_to_template": scm_version_template,
    },
    package_dir={"": "python"},
    packages=find_namespace_packages(where="python"),
    package_data={"": ["*.rst", "*.yaml"]},
    scripts=["bin/atmonochromator_csc.py"],
    license="GPL",
)
