{% set data= load_setup_py_data() %}

package:
  name: ts-atmonochromator
  version: {{ data.get('version') }}

source:
  path: ../

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

test:
  requires:
    - ts-conda-build =0.4
    - ts-salobj {{salobj_version}}
    - ts-idl {{idl_version}}
  commands:
    - pytest
    - run_atmonochromator -h
  imports:
    - lsst.ts.atmonochromator
  source_files:
    - tests
    - pyproject.toml

requirements:
  host:
    - python {{python}}
    - pip
    - setuptools_scm
    - setuptools
  build:
    - python {{python}}
    - ts-conda-build =0.4
  run:
    - python {{python}}
    - setuptools
    - setuptools_scm
    - ts-idl
    - ts-salobj
    - ts-tcpip
