settingVersions:
  recommendedSettingsVersion: 'default'
  recommendedSettingsLabels: ['default', 'simulation']

setting:
  default:
    host: '10.0.100.122'  # IP of the controller
    port: 50000
  simulation:
    host: '127.0.0.1'
    port: 50000
    simulation: 1
